<template>
    <el-popover placement="bottom" :width="width" trigger="click" v-model="iconShow">
        <div class="icon-box">
            <el-button class="icon" v-for="(item,i) in list" :type="selected==item.name?'primary':''" size="mini" :key="i" :icon="item.name" @click="onSelected(item)"></el-button>
        </div>
        <div class="icon-btns">
            <el-button size="small" icon="el-icon-error" @click="onClose">清除</el-button>
            <el-button size="small" icon="el-icon-success" type="primary" @click="onSubmit">确定</el-button>
        </div>
        <div slot="reference" class="el-input--suffix" :style="'width:'+width+'px;height:40px;position:relative;'">
            <div class="el-input__inner">{{selected?selected:placeholder}}</div>
            <span class="el-input__suffix">
                <i v-if="iconShow" class="el-input__icon el-icon-arrow-up"></i>
                <i v-else class="el-input__icon el-icon-arrow-down"></i>
            </span>
        </div>
    </el-popover>
</template>

<script>
export default {
    props:{
        value:{type:String,default(){return "";}},
        width:{type:Number,default(){return 400;}},
        placeholder:{type:String,default(){return "请选择图标";}}
    },
    data(){
        return {
            iconShow:false,
            list:[],
            selected:""
        }
    },
    watch:{
        value(v,ov){
            this.selected=v;
        }
    },
    methods:{
        onSelected(item){
            this.selected=item.name;
        },
        onClose(){
            this.selected="";
            this.iconShow=false;
        },
        onSubmit(){
            this.iconShow=false;
            this.$emit("input",this.selected);
        }
    },
    mounted(){
        this.selected=this.value;
        this.list=[
            {"id": 0,"name": "fa fa-bars fa-lg"},
            {"id": 1,"name": "fa fa-font-awesome"},
            {"id": 2,"name": "fa fa-caret-down"},
            {"id": 3,"name": "fa fa-flag fa-fw"},
            {"id": 4,"name": "fa fa-handshake-o fa-fw"},
            {"id": 5,"name": "fa fa-camera-retro fa-fw"},
            {"id": 6,"name": "fa fa-universal-access fa-fw"},
            {"id": 7,"name": "fa fa-hand-spock-o fa-fw"},
            {"id": 8,"name": "fa fa-ship fa-fw"},
            {"id": 9,"name": "fa fa-venus fa-fw"},
            {"id": 10,"name": "fa fa-file-image-o fa-fw"},
            {"id": 11,"name": "fa fa-spinner fa-fw"},
            {"id": 12,"name": "fa fa-check-square fa-fw"},
            {"id": 13,"name": "fa fa-credit-card fa-fw"},
            {"id": 14,"name": "fa fa-pie-chart fa-fw"},
            {"id": 15,"name": "fa fa-won fa-fw"},
            {"id": 16,"name": "fa fa-file-text-o fa-fw"},
            {"id": 17,"name": "fa fa-arrow-right fa-fw"},
            {"id": 18,"name": "fa fa-play-circle fa-fw"},
            {"id": 19,"name": "fa fa-facebook-official fa-fw"},
            {"id": 20,"name": "fa fa-medkit fa-fw"},
            {"id": 21,"name": "fa fa-universal-access"},
            {"id": 22,"name": "fa fa-flag"},
            {"id": 23,"name": "fa fa-envelope"},
            {"id": 24,"name": "fa fa-search"},
            {"id": 25,"name": "fa fa-times-circle hide"},
            {"id": 28,"name": "fa fa-address-book"},
            {"id": 29,"name": "fa fa-address-book-o"},
            {"id": 30,"name": "fa fa-address-card"},
            {"id": 31,"name": "fa fa-address-card-o"},
            {"id": 32,"name": "fa fa-bandcamp"},
            {"id": 33,"name": "fa fa-bath"},
            {"id": 34,"name": "fa fa-bathtub"},
            {"id": 35,"name": "fa fa-drivers-license"},
            {"id": 36,"name": "fa fa-drivers-license-o"},
            {"id": 37,"name": "fa fa-eercast"},
            {"id": 38,"name": "fa fa-envelope-open"},
            {"id": 39,"name": "fa fa-envelope-open-o"},
            {"id": 40,"name": "fa fa-etsy"},
            {"id": 41,"name": "fa fa-free-code-camp"},
            {"id": 42,"name": "fa fa-grav"},
            {"id": 43,"name": "fa fa-handshake-o"},
            {"id": 44,"name": "fa fa-id-badge"},
            {"id": 45,"name": "fa fa-id-card"},
            {"id": 46,"name": "fa fa-id-card-o"},
            {"id": 47,"name": "fa fa-imdb"},
            {"id": 48,"name": "fa fa-linode"},
            {"id": 49,"name": "fa fa-meetup"},
            {"id": 50,"name": "fa fa-microchip"},
            {"id": 51,"name": "fa fa-podcast"},
            {"id": 52,"name": "fa fa-quora"},
            {"id": 53,"name": "fa fa-ravelry"},
            {"id": 54,"name": "fa fa-s15"},
            {"id": 55,"name": "fa fa-shower"},
            {"id": 56,"name": "fa fa-snowflake-o"},
            {"id": 57,"name": "fa fa-superpowers"},
            {"id": 58,"name": "fa fa-telegram"},
            {"id": 59,"name": "fa fa-thermometer"},
            {"id": 60,"name": "fa fa-thermometer-0"},
            {"id": 61,"name": "fa fa-thermometer-1"},
            {"id": 62,"name": "fa fa-thermometer-2"},
            {"id": 63,"name": "fa fa-thermometer-3"},
            {"id": 64,"name": "fa fa-thermometer-4"},
            {"id": 65,"name": "fa fa-thermometer-empty"},
            {"id": 66,"name": "fa fa-thermometer-full"},
            {"id": 67,"name": "fa fa-thermometer-half"},
            {"id": 68,"name": "fa fa-thermometer-quarter"},
            {"id": 69,"name": "fa fa-thermometer-three-quarters"},
            {"id": 70,"name": "fa fa-times-rectangle"},
            {"id": 71,"name": "fa fa-times-rectangle-o"},
            {"id": 72,"name": "fa fa-user-circle"},
            {"id": 73,"name": "fa fa-user-circle-o"},
            {"id": 74,"name": "fa fa-user-o"},
            {"id": 75,"name": "fa fa-vcard"},
            {"id": 76,"name": "fa fa-vcard-o"},
            {"id": 77,"name": "fa fa-window-close"},
            {"id": 78,"name": "fa fa-window-close-o"},
            {"id": 79,"name": "fa fa-window-maximize"},
            {"id": 80,"name": "fa fa-window-minimize"},
            {"id": 81,"name": "fa fa-window-restore"},
            {"id": 82,"name": "fa fa-wpexplorer"},
            {"id": 83,"name": "fa fa-adjust"},
            {"id": 84,"name": "fa fa-american-sign-language-interpreting"},
            {"id": 85,"name": "fa fa-anchor"},
            {"id": 86,"name": "fa fa-archive"},
            {"id": 87,"name": "fa fa-area-chart"},
            {"id": 88,"name": "fa fa-arrows"},
            {"id": 89,"name": "fa fa-arrows-h"},
            {"id": 90,"name": "fa fa-arrows-v"},
            {"id": 91,"name": "fa fa-asl-interpreting"},
            {"id": 92,"name": "fa fa-assistive-listening-systems"},
            {"id": 93,"name": "fa fa-asterisk"},
            {"id": 94,"name": "fa fa-at"},
            {"id": 95,"name": "fa fa-audio-description"},
            {"id": 96,"name": "fa fa-automobile"},
            {"id": 97,"name": "fa fa-balance-scale"},
            {"id": 98,"name": "fa fa-ban"},
            {"id": 99,"name": "fa fa-bank"},
            {"id": 100,"name": "fa fa-bar-chart"},
            {"id": 101,"name": "fa fa-bar-chart-o"},
            {"id": 102,"name": "fa fa-barcode"},
            {"id": 103,"name": "fa fa-bars"},
            {"id": 104,"name": "fa fa-battery"},
            {"id": 105,"name": "fa fa-battery-0"},
            {"id": 106,"name": "fa fa-battery-1"},
            {"id": 107,"name": "fa fa-battery-2"},
            {"id": 108,"name": "fa fa-battery-3"},
            {"id": 109,"name": "fa fa-battery-4"},
            {"id": 110,"name": "fa fa-battery-empty"},
            {"id": 111,"name": "fa fa-battery-full"},
            {"id": 112,"name": "fa fa-battery-half"},
            {"id": 113,"name": "fa fa-battery-quarter"},
            {"id": 114,"name": "fa fa-battery-three-quarters"},
            {"id": 115,"name": "fa fa-bed"},
            {"id": 116,"name": "fa fa-beer"},
            {"id": 117,"name": "fa fa-bell"},
            {"id": 118,"name": "fa fa-bell-o"},
            {"id": 119,"name": "fa fa-bell-slash"},
            {"id": 120,"name": "fa fa-bell-slash-o"},
            {"id": 121,"name": "fa fa-bicycle"},
            {"id": 122,"name": "fa fa-binoculars"},
            {"id": 123,"name": "fa fa-birthday-cake"},
            {"id": 124,"name": "fa fa-blind"},
            {"id": 125,"name": "fa fa-bluetooth"},
            {"id": 126,"name": "fa fa-bluetooth-b"},
            {"id": 127,"name": "fa fa-bolt"},
            {"id": 128,"name": "fa fa-bomb"},
            {"id": 129,"name": "fa fa-book"},
            {"id": 130,"name": "fa fa-bookmark"},
            {"id": 131,"name": "fa fa-bookmark-o"},
            {"id": 132,"name": "fa fa-braille"},
            {"id": 133,"name": "fa fa-briefcase"},
            {"id": 134,"name": "fa fa-bug"},
            {"id": 135,"name": "fa fa-building"},
            {"id": 136,"name": "fa fa-building-o"},
            {"id": 137,"name": "fa fa-bullhorn"},
            {"id": 138,"name": "fa fa-bullseye"},
            {"id": 139,"name": "fa fa-bus"},
            {"id": 140,"name": "fa fa-cab"},
            {"id": 141,"name": "fa fa-calculator"},
            {"id": 142,"name": "fa fa-calendar"},
            {"id": 143,"name": "fa fa-calendar-check-o"},
            {"id": 144,"name": "fa fa-calendar-minus-o"},
            {"id": 145,"name": "fa fa-calendar-o"},
            {"id": 146,"name": "fa fa-calendar-plus-o"},
            {"id": 147,"name": "fa fa-calendar-times-o"},
            {"id": 148,"name": "fa fa-camera"},
            {"id": 149,"name": "fa fa-camera-retro"},
            {"id": 150,"name": "fa fa-car"},
            {"id": 151,"name": "fa fa-caret-square-o-down"},
            {"id": 152,"name": "fa fa-caret-square-o-left"},
            {"id": 153,"name": "fa fa-caret-square-o-right"},
            {"id": 154,"name": "fa fa-caret-square-o-up"},
            {"id": 155,"name": "fa fa-cart-arrow-down"},
            {"id": 156,"name": "fa fa-cart-plus"},
            {"id": 157,"name": "fa fa-cc"},
            {"id": 158,"name": "fa fa-certificate"},
            {"id": 159,"name": "fa fa-check"},
            {"id": 160,"name": "fa fa-check-circle"},
            {"id": 161,"name": "fa fa-check-circle-o"},
            {"id": 162,"name": "fa fa-check-square"},
            {"id": 163,"name": "fa fa-check-square-o"},
            {"id": 164,"name": "fa fa-child"},
            {"id": 165,"name": "fa fa-circle"},
            {"id": 166,"name": "fa fa-circle-o"},
            {"id": 167,"name": "fa fa-circle-o-notch"},
            {"id": 168,"name": "fa fa-circle-thin"},
            {"id": 169,"name": "fa fa-clock-o"},
            {"id": 170,"name": "fa fa-clone"},
            {"id": 171,"name": "fa fa-close"},
            {"id": 172,"name": "fa fa-cloud"},
            {"id": 173,"name": "fa fa-cloud-download"},
            {"id": 174,"name": "fa fa-cloud-upload"},
            {"id": 175,"name": "fa fa-code"},
            {"id": 176,"name": "fa fa-code-fork"},
            {"id": 177,"name": "fa fa-coffee"},
            {"id": 178,"name": "fa fa-cog"},
            {"id": 179,"name": "fa fa-cogs"},
            {"id": 180,"name": "fa fa-comment"},
            {"id": 181,"name": "fa fa-comment-o"},
            {"id": 182,"name": "fa fa-commenting"},
            {"id": 183,"name": "fa fa-commenting-o"},
            {"id": 184,"name": "fa fa-comments"},
            {"id": 185,"name": "fa fa-comments-o"},
            {"id": 186,"name": "fa fa-compass"},
            {"id": 187,"name": "fa fa-copyright"},
            {"id": 188,"name": "fa fa-creative-commons"},
            {"id": 189,"name": "fa fa-credit-card"},
            {"id": 190,"name": "fa fa-credit-card-alt"},
            {"id": 191,"name": "fa fa-crop"},
            {"id": 192,"name": "fa fa-crosshairs"},
            {"id": 193,"name": "fa fa-cube"},
            {"id": 194,"name": "fa fa-cubes"},
            {"id": 195,"name": "fa fa-cutlery"},
            {"id": 196,"name": "fa fa-dashboard"},
            {"id": 197,"name": "fa fa-database"},
            {"id": 198,"name": "fa fa-deaf"},
            {"id": 199,"name": "fa fa-deafness"},
            {"id": 200,"name": "fa fa-desktop"},
            {"id": 201,"name": "fa fa-diamond"},
            {"id": 202,"name": "fa fa-dot-circle-o"},
            {"id": 203,"name": "fa fa-download"},
            {"id": 204,"name": "fa fa-edit"},
            {"id": 205,"name": "fa fa-ellipsis-h"},
            {"id": 206,"name": "fa fa-ellipsis-v"},
            {"id": 207,"name": "fa fa-envelope-o"},
            {"id": 208,"name": "fa fa-envelope-square"},
            {"id": 209,"name": "fa fa-eraser"},
            {"id": 210,"name": "fa fa-exchange"},
            {"id": 211,"name": "fa fa-exclamation"},
            {"id": 212,"name": "fa fa-exclamation-circle"},
            {"id": 213,"name": "fa fa-exclamation-triangle"},
            {"id": 214,"name": "fa fa-external-link"},
            {"id": 215,"name": "fa fa-external-link-square"},
            {"id": 216,"name": "fa fa-eye"},
            {"id": 217,"name": "fa fa-eye-slash"},
            {"id": 218,"name": "fa fa-eyedropper"},
            {"id": 219,"name": "fa fa-fax"},
            {"id": 220,"name": "fa fa-feed"},
            {"id": 221,"name": "fa fa-female"},
            {"id": 222,"name": "fa fa-fighter-jet"},
            {"id": 223,"name": "fa fa-file-archive-o"},
            {"id": 224,"name": "fa fa-file-audio-o"},
            {"id": 225,"name": "fa fa-file-code-o"},
            {"id": 226,"name": "fa fa-file-excel-o"},
            {"id": 227,"name": "fa fa-file-image-o"},
            {"id": 228,"name": "fa fa-file-movie-o"},
            {"id": 229,"name": "fa fa-file-pdf-o"},
            {"id": 230,"name": "fa fa-file-photo-o"},
            {"id": 231,"name": "fa fa-file-picture-o"},
            {"id": 232,"name": "fa fa-file-powerpoint-o"},
            {"id": 233,"name": "fa fa-file-sound-o"},
            {"id": 234,"name": "fa fa-file-video-o"},
            {"id": 235,"name": "fa fa-file-word-o"},
            {"id": 236,"name": "fa fa-file-zip-o"},
            {"id": 237,"name": "fa fa-film"},
            {"id": 238,"name": "fa fa-filter"},
            {"id": 239,"name": "fa fa-fire"},
            {"id": 240,"name": "fa fa-fire-extinguisher"},
            {"id": 241,"name": "fa fa-flag-checkered"},
            {"id": 242,"name": "fa fa-flag-o"},
            {"id": 243,"name": "fa fa-flash"},
            {"id": 244,"name": "fa fa-flask"},
            {"id": 245,"name": "fa fa-folder"},
            {"id": 246,"name": "fa fa-folder-o"},
            {"id": 247,"name": "fa fa-folder-open"},
            {"id": 248,"name": "fa fa-folder-open-o"},
            {"id": 249,"name": "fa fa-frown-o"},
            {"id": 250,"name": "fa fa-futbol-o"},
            {"id": 251,"name": "fa fa-gamepad"},
            {"id": 252,"name": "fa fa-gavel"},
            {"id": 253,"name": "fa fa-gear"},
            {"id": 254,"name": "fa fa-gears"},
            {"id": 255,"name": "fa fa-gift"},
            {"id": 256,"name": "fa fa-glass"},
            {"id": 257,"name": "fa fa-globe"},
            {"id": 258,"name": "fa fa-graduation-cap"},
            {"id": 259,"name": "fa fa-group"},
            {"id": 260,"name": "fa fa-hand-grab-o"},
            {"id": 261,"name": "fa fa-hand-lizard-o"},
            {"id": 262,"name": "fa fa-hand-paper-o"},
            {"id": 263,"name": "fa fa-hand-peace-o"},
            {"id": 264,"name": "fa fa-hand-pointer-o"},
            {"id": 265,"name": "fa fa-hand-rock-o"},
            {"id": 266,"name": "fa fa-hand-scissors-o"},
            {"id": 267,"name": "fa fa-hand-spock-o"},
            {"id": 268,"name": "fa fa-hand-stop-o"},
            {"id": 269,"name": "fa fa-hard-of-hearing"},
            {"id": 270,"name": "fa fa-hashtag"},
            {"id": 271,"name": "fa fa-hdd-o"},
            {"id": 272,"name": "fa fa-headphones"},
            {"id": 273,"name": "fa fa-heart"},
            {"id": 274,"name": "fa fa-heart-o"},
            {"id": 275,"name": "fa fa-heartbeat"},
            {"id": 276,"name": "fa fa-history"},
            {"id": 277,"name": "fa fa-home"},
            {"id": 278,"name": "fa fa-hotel"},
            {"id": 279,"name": "fa fa-hourglass"},
            {"id": 280,"name": "fa fa-hourglass-1"},
            {"id": 281,"name": "fa fa-hourglass-2"},
            {"id": 282,"name": "fa fa-hourglass-3"},
            {"id": 283,"name": "fa fa-hourglass-end"},
            {"id": 284,"name": "fa fa-hourglass-half"},
            {"id": 285,"name": "fa fa-hourglass-o"},
            {"id": 286,"name": "fa fa-hourglass-start"},
            {"id": 287,"name": "fa fa-i-cursor"},
            {"id": 288,"name": "fa fa-image"},
            {"id": 289,"name": "fa fa-inbox"},
            {"id": 290,"name": "fa fa-industry"},
            {"id": 291,"name": "fa fa-info"},
            {"id": 292,"name": "fa fa-info-circle"},
            {"id": 293,"name": "fa fa-institution"},
            {"id": 294,"name": "fa fa-key"},
            {"id": 295,"name": "fa fa-keyboard-o"},
            {"id": 296,"name": "fa fa-language"},
            {"id": 297,"name": "fa fa-laptop"},
            {"id": 298,"name": "fa fa-leaf"},
            {"id": 299,"name": "fa fa-legal"},
            {"id": 300,"name": "fa fa-lemon-o"},
            {"id": 301,"name": "fa fa-level-down"},
            {"id": 302,"name": "fa fa-level-up"},
            {"id": 303,"name": "fa fa-life-bouy"},
            {"id": 304,"name": "fa fa-life-buoy"},
            {"id": 305,"name": "fa fa-life-ring"},
            {"id": 306,"name": "fa fa-life-saver"},
            {"id": 307,"name": "fa fa-lightbulb-o"},
            {"id": 308,"name": "fa fa-line-chart"},
            {"id": 309,"name": "fa fa-location-arrow"},
            {"id": 310,"name": "fa fa-lock"},
            {"id": 311,"name": "fa fa-low-vision"},
            {"id": 312,"name": "fa fa-magic"},
            {"id": 313,"name": "fa fa-magnet"},
            {"id": 314,"name": "fa fa-mail-forward"},
            {"id": 315,"name": "fa fa-mail-reply"},
            {"id": 316,"name": "fa fa-mail-reply-all"},
            {"id": 317,"name": "fa fa-male"},
            {"id": 318,"name": "fa fa-map"},
            {"id": 319,"name": "fa fa-map-marker"},
            {"id": 320,"name": "fa fa-map-o"},
            {"id": 321,"name": "fa fa-map-pin"},
            {"id": 322,"name": "fa fa-map-signs"},
            {"id": 323,"name": "fa fa-meh-o"},
            {"id": 324,"name": "fa fa-microphone"},
            {"id": 325,"name": "fa fa-microphone-slash"},
            {"id": 326,"name": "fa fa-minus"},
            {"id": 327,"name": "fa fa-minus-circle"},
            {"id": 328,"name": "fa fa-minus-square"},
            {"id": 329,"name": "fa fa-minus-square-o"},
            {"id": 330,"name": "fa fa-mobile"},
            {"id": 331,"name": "fa fa-mobile-phone"},
            {"id": 332,"name": "fa fa-money"},
            {"id": 333,"name": "fa fa-moon-o"},
            {"id": 334,"name": "fa fa-mortar-board"},
            {"id": 335,"name": "fa fa-motorcycle"},
            {"id": 336,"name": "fa fa-mouse-pointer"},
            {"id": 337,"name": "fa fa-music"},
            {"id": 338,"name": "fa fa-navicon"},
            {"id": 339,"name": "fa fa-newspaper-o"},
            {"id": 340,"name": "fa fa-object-group"},
            {"id": 341,"name": "fa fa-object-ungroup"},
            {"id": 342,"name": "fa fa-paint-brush"},
            {"id": 343,"name": "fa fa-paper-plane"},
            {"id": 344,"name": "fa fa-paper-plane-o"},
            {"id": 345,"name": "fa fa-paw"},
            {"id": 346,"name": "fa fa-pencil"},
            {"id": 347,"name": "fa fa-pencil-square"},
            {"id": 348,"name": "fa fa-pencil-square-o"},
            {"id": 349,"name": "fa fa-percent"},
            {"id": 350,"name": "fa fa-phone"},
            {"id": 351,"name": "fa fa-phone-square"},
            {"id": 352,"name": "fa fa-photo"},
            {"id": 353,"name": "fa fa-picture-o"},
            {"id": 354,"name": "fa fa-pie-chart"},
            {"id": 355,"name": "fa fa-plane"},
            {"id": 356,"name": "fa fa-plug"},
            {"id": 357,"name": "fa fa-plus"},
            {"id": 358,"name": "fa fa-plus-circle"},
            {"id": 359,"name": "fa fa-plus-square"},
            {"id": 360,"name": "fa fa-plus-square-o"},
            {"id": 361,"name": "fa fa-power-off"},
            {"id": 362,"name": "fa fa-print"},
            {"id": 363,"name": "fa fa-puzzle-piece"},
            {"id": 364,"name": "fa fa-qrcode"},
            {"id": 365,"name": "fa fa-question"},
            {"id": 366,"name": "fa fa-question-circle"},
            {"id": 367,"name": "fa fa-question-circle-o"},
            {"id": 368,"name": "fa fa-quote-left"},
            {"id": 369,"name": "fa fa-quote-right"},
            {"id": 370,"name": "fa fa-random"},
            {"id": 371,"name": "fa fa-recycle"},
            {"id": 372,"name": "fa fa-refresh"},
            {"id": 373,"name": "fa fa-registered"},
            {"id": 374,"name": "fa fa-remove"},
            {"id": 375,"name": "fa fa-reorder"},
            {"id": 376,"name": "fa fa-reply"},
            {"id": 377,"name": "fa fa-reply-all"},
            {"id": 378,"name": "fa fa-retweet"},
            {"id": 379,"name": "fa fa-road"},
            {"id": 380,"name": "fa fa-rocket"},
            {"id": 381,"name": "fa fa-rss"},
            {"id": 382,"name": "fa fa-rss-square"},
            {"id": 383,"name": "fa fa-search-minus"},
            {"id": 384,"name": "fa fa-search-plus"},
            {"id": 385,"name": "fa fa-send"},
            {"id": 386,"name": "fa fa-send-o"},
            {"id": 387,"name": "fa fa-server"},
            {"id": 388,"name": "fa fa-share"},
            {"id": 389,"name": "fa fa-share-alt"},
            {"id": 390,"name": "fa fa-share-alt-square"},
            {"id": 391,"name": "fa fa-share-square"},
            {"id": 392,"name": "fa fa-share-square-o"},
            {"id": 393,"name": "fa fa-shield"},
            {"id": 394,"name": "fa fa-ship"},
            {"id": 395,"name": "fa fa-shopping-bag"},
            {"id": 396,"name": "fa fa-shopping-basket"},
            {"id": 397,"name": "fa fa-shopping-cart"},
            {"id": 398,"name": "fa fa-sign-in"},
            {"id": 399,"name": "fa fa-sign-language"},
            {"id": 400,"name": "fa fa-sign-out"},
            {"id": 401,"name": "fa fa-signal"},
            {"id": 402,"name": "fa fa-signing"},
            {"id": 403,"name": "fa fa-sitemap"},
            {"id": 404,"name": "fa fa-sliders"},
            {"id": 405,"name": "fa fa-smile-o"},
            {"id": 406,"name": "fa fa-soccer-ball-o"},
            {"id": 407,"name": "fa fa-sort"},
            {"id": 408,"name": "fa fa-sort-alpha-asc"},
            {"id": 409,"name": "fa fa-sort-alpha-desc"},
            {"id": 410,"name": "fa fa-sort-amount-asc"},
            {"id": 411,"name": "fa fa-sort-amount-desc"},
            {"id": 412,"name": "fa fa-sort-asc"},
            {"id": 413,"name": "fa fa-sort-desc"},
            {"id": 414,"name": "fa fa-sort-down"},
            {"id": 415,"name": "fa fa-sort-numeric-asc"},
            {"id": 416,"name": "fa fa-sort-numeric-desc"},
            {"id": 417,"name": "fa fa-sort-up"},
            {"id": 418,"name": "fa fa-space-shuttle"},
            {"id": 419,"name": "fa fa-spinner"},
            {"id": 420,"name": "fa fa-spoon"},
            {"id": 421,"name": "fa fa-square"},
            {"id": 422,"name": "fa fa-square-o"},
            {"id": 423,"name": "fa fa-star"},
            {"id": 424,"name": "fa fa-star-half"},
            {"id": 425,"name": "fa fa-star-half-empty"},
            {"id": 426,"name": "fa fa-star-half-full"},
            {"id": 427,"name": "fa fa-star-half-o"},
            {"id": 428,"name": "fa fa-star-o"},
            {"id": 429,"name": "fa fa-sticky-note"},
            {"id": 430,"name": "fa fa-sticky-note-o"},
            {"id": 431,"name": "fa fa-street-view"},
            {"id": 432,"name": "fa fa-suitcase"},
            {"id": 433,"name": "fa fa-sun-o"},
            {"id": 434,"name": "fa fa-support"},
            {"id": 435,"name": "fa fa-tablet"},
            {"id": 436,"name": "fa fa-tachometer"},
            {"id": 437,"name": "fa fa-tag"},
            {"id": 438,"name": "fa fa-tags"},
            {"id": 439,"name": "fa fa-tasks"},
            {"id": 440,"name": "fa fa-taxi"},
            {"id": 441,"name": "fa fa-television"},
            {"id": 442,"name": "fa fa-terminal"},
            {"id": 443,"name": "fa fa-thumb-tack"},
            {"id": 444,"name": "fa fa-thumbs-down"},
            {"id": 445,"name": "fa fa-thumbs-o-down"},
            {"id": 446,"name": "fa fa-thumbs-o-up"},
            {"id": 447,"name": "fa fa-thumbs-up"},
            {"id": 448,"name": "fa fa-ticket"},
            {"id": 449,"name": "fa fa-times"},
            {"id": 450,"name": "fa fa-times-circle"},
            {"id": 451,"name": "fa fa-times-circle-o"},
            {"id": 452,"name": "fa fa-tint"},
            {"id": 453,"name": "fa fa-toggle-down"},
            {"id": 454,"name": "fa fa-toggle-left"},
            {"id": 455,"name": "fa fa-toggle-off"},
            {"id": 456,"name": "fa fa-toggle-on"},
            {"id": 457,"name": "fa fa-toggle-right"},
            {"id": 458,"name": "fa fa-toggle-up"},
            {"id": 459,"name": "fa fa-trademark"},
            {"id": 460,"name": "fa fa-trash"},
            {"id": 461,"name": "fa fa-trash-o"},
            {"id": 462,"name": "fa fa-tree"},
            {"id": 463,"name": "fa fa-trophy"},
            {"id": 464,"name": "fa fa-truck"},
            {"id": 465,"name": "fa fa-tty"},
            {"id": 466,"name": "fa fa-tv"},
            {"id": 467,"name": "fa fa-umbrella"},
            {"id": 468,"name": "fa fa-university"},
            {"id": 469,"name": "fa fa-unlock"},
            {"id": 470,"name": "fa fa-unlock-alt"},
            {"id": 471,"name": "fa fa-unsorted"},
            {"id": 472,"name": "fa fa-upload"},
            {"id": 473,"name": "fa fa-user"},
            {"id": 474,"name": "fa fa-user-plus"},
            {"id": 475,"name": "fa fa-user-secret"},
            {"id": 476,"name": "fa fa-user-times"},
            {"id": 477,"name": "fa fa-users"},
            {"id": 478,"name": "fa fa-video-camera"},
            {"id": 479,"name": "fa fa-volume-control-phone"},
            {"id": 480,"name": "fa fa-volume-down"},
            {"id": 481,"name": "fa fa-volume-off"},
            {"id": 482,"name": "fa fa-volume-up"},
            {"id": 483,"name": "fa fa-warning"},
            {"id": 484,"name": "fa fa-wheelchair"},
            {"id": 485,"name": "fa fa-wheelchair-alt"},
            {"id": 486,"name": "fa fa-wifi"},
            {"id": 487,"name": "fa fa-wrench"},
            {"id": 488,"name": "fa fa-hand-o-down"},
            {"id": 489,"name": "fa fa-hand-o-left"},
            {"id": 490,"name": "fa fa-hand-o-right"},
            {"id": 491,"name": "fa fa-hand-o-up"},
            {"id": 492,"name": "fa fa-ambulance"},
            {"id": 493,"name": "fa fa-subway"},
            {"id": 494,"name": "fa fa-train"},
            {"id": 495,"name": "fa fa-genderless"},
            {"id": 496,"name": "fa fa-intersex"},
            {"id": 497,"name": "fa fa-mars"},
            {"id": 498,"name": "fa fa-mars-double"},
            {"id": 499,"name": "fa fa-mars-stroke"},
            {"id": 500,"name": "fa fa-mars-stroke-h"},
            {"id": 501,"name": "fa fa-mars-stroke-v"},
            {"id": 502,"name": "fa fa-mercury"},
            {"id": 503,"name": "fa fa-neuter"},
            {"id": 504,"name": "fa fa-transgender"},
            {"id": 505,"name": "fa fa-transgender-alt"},
            {"id": 506,"name": "fa fa-venus"},
            {"id": 507,"name": "fa fa-venus-double"},
            {"id": 508,"name": "fa fa-venus-mars"},
            {"id": 509,"name": "fa fa-file"},
            {"id": 510,"name": "fa fa-file-o"},
            {"id": 511,"name": "fa fa-file-text"},
            {"id": 512,"name": "fa fa-file-text-o"},
            {"id": 515,"name": "fa fa-cc-amex"},
            {"id": 516,"name": "fa fa-cc-diners-club"},
            {"id": 517,"name": "fa fa-cc-discover"},
            {"id": 518,"name": "fa fa-cc-jcb"},
            {"id": 519,"name": "fa fa-cc-mastercard"},
            {"id": 520,"name": "fa fa-cc-paypal"},
            {"id": 521,"name": "fa fa-cc-stripe"},
            {"id": 522,"name": "fa fa-cc-visa"},
            {"id": 523,"name": "fa fa-google-wallet"},
            {"id": 524,"name": "fa fa-paypal"},
            {"id": 525,"name": "fa fa-bitcoin"},
            {"id": 526,"name": "fa fa-btc"},
            {"id": 527,"name": "fa fa-cny"},
            {"id": 528,"name": "fa fa-dollar"},
            {"id": 529,"name": "fa fa-eur"},
            {"id": 530,"name": "fa fa-euro"},
            {"id": 531,"name": "fa fa-gbp"},
            {"id": 532,"name": "fa fa-gg"},
            {"id": 533,"name": "fa fa-gg-circle"},
            {"id": 534,"name": "fa fa-ils"},
            {"id": 535,"name": "fa fa-inr"},
            {"id": 536,"name": "fa fa-jpy"},
            {"id": 537,"name": "fa fa-krw"},
            {"id": 538,"name": "fa fa-rmb"},
            {"id": 539,"name": "fa fa-rouble"},
            {"id": 540,"name": "fa fa-rub"},
            {"id": 541,"name": "fa fa-ruble"},
            {"id": 542,"name": "fa fa-rupee"},
            {"id": 543,"name": "fa fa-shekel"},
            {"id": 544,"name": "fa fa-sheqel"},
            {"id": 545,"name": "fa fa-try"},
            {"id": 546,"name": "fa fa-turkish-lira"},
            {"id": 547,"name": "fa fa-usd"},
            {"id": 548,"name": "fa fa-won"},
            {"id": 549,"name": "fa fa-yen"},
            {"id": 550,"name": "fa fa-align-center"},
            {"id": 551,"name": "fa fa-align-justify"},
            {"id": 552,"name": "fa fa-align-left"},
            {"id": 553,"name": "fa fa-align-right"},
            {"id": 554,"name": "fa fa-bold"},
            {"id": 555,"name": "fa fa-chain"},
            {"id": 556,"name": "fa fa-chain-broken"},
            {"id": 557,"name": "fa fa-clipboard"},
            {"id": 558,"name": "fa fa-columns"},
            {"id": 559,"name": "fa fa-copy"},
            {"id": 560,"name": "fa fa-cut"},
            {"id": 561,"name": "fa fa-dedent"},
            {"id": 562,"name": "fa fa-files-o"},
            {"id": 563,"name": "fa fa-floppy-o"},
            {"id": 564,"name": "fa fa-font"},
            {"id": 565,"name": "fa fa-header"},
            {"id": 566,"name": "fa fa-indent"},
            {"id": 567,"name": "fa fa-italic"},
            {"id": 568,"name": "fa fa-link"},
            {"id": 569,"name": "fa fa-list"},
            {"id": 570,"name": "fa fa-list-alt"},
            {"id": 571,"name": "fa fa-list-ol"},
            {"id": 572,"name": "fa fa-list-ul"},
            {"id": 573,"name": "fa fa-outdent"},
            {"id": 574,"name": "fa fa-paperclip"},
            {"id": 575,"name": "fa fa-paragraph"},
            {"id": 576,"name": "fa fa-paste"},
            {"id": 577,"name": "fa fa-repeat"},
            {"id": 578,"name": "fa fa-rotate-left"},
            {"id": 579,"name": "fa fa-rotate-right"},
            {"id": 580,"name": "fa fa-save"},
            {"id": 581,"name": "fa fa-scissors"},
            {"id": 582,"name": "fa fa-strikethrough"},
            {"id": 583,"name": "fa fa-subscript"},
            {"id": 584,"name": "fa fa-superscript"},
            {"id": 585,"name": "fa fa-table"},
            {"id": 586,"name": "fa fa-text-height"},
            {"id": 587,"name": "fa fa-text-width"},
            {"id": 588,"name": "fa fa-th"},
            {"id": 589,"name": "fa fa-th-large"},
            {"id": 590,"name": "fa fa-th-list"},
            {"id": 591,"name": "fa fa-underline"},
            {"id": 592,"name": "fa fa-undo"},
            {"id": 593,"name": "fa fa-unlink"},
            {"id": 594,"name": "fa fa-angle-double-down"},
            {"id": 595,"name": "fa fa-angle-double-left"},
            {"id": 596,"name": "fa fa-angle-double-right"},
            {"id": 597,"name": "fa fa-angle-double-up"},
            {"id": 598,"name": "fa fa-angle-down"},
            {"id": 599,"name": "fa fa-angle-left"},
            {"id": 600,"name": "fa fa-angle-right"},
            {"id": 601,"name": "fa fa-angle-up"},
            {"id": 602,"name": "fa fa-arrow-circle-down"},
            {"id": 603,"name": "fa fa-arrow-circle-left"},
            {"id": 604,"name": "fa fa-arrow-circle-o-down"},
            {"id": 605,"name": "fa fa-arrow-circle-o-left"},
            {"id": 606,"name": "fa fa-arrow-circle-o-right"},
            {"id": 607,"name": "fa fa-arrow-circle-o-up"},
            {"id": 608,"name": "fa fa-arrow-circle-right"},
            {"id": 609,"name": "fa fa-arrow-circle-up"},
            {"id": 610,"name": "fa fa-arrow-down"},
            {"id": 611,"name": "fa fa-arrow-left"},
            {"id": 612,"name": "fa fa-arrow-right"},
            {"id": 613,"name": "fa fa-arrow-up"},
            {"id": 614,"name": "fa fa-arrows-alt"},
            {"id": 615,"name": "fa fa-caret-left"},
            {"id": 616,"name": "fa fa-caret-right"},
            {"id": 617,"name": "fa fa-caret-up"},
            {"id": 618,"name": "fa fa-chevron-circle-down"},
            {"id": 619,"name": "fa fa-chevron-circle-left"},
            {"id": 620,"name": "fa fa-chevron-circle-right"},
            {"id": 621,"name": "fa fa-chevron-circle-up"},
            {"id": 622,"name": "fa fa-chevron-down"},
            {"id": 623,"name": "fa fa-chevron-left"},
            {"id": 624,"name": "fa fa-chevron-right"},
            {"id": 625,"name": "fa fa-chevron-up"},
            {"id": 626,"name": "fa fa-long-arrow-down"},
            {"id": 627,"name": "fa fa-long-arrow-left"},
            {"id": 628,"name": "fa fa-long-arrow-right"},
            {"id": 629,"name": "fa fa-long-arrow-up"},
            {"id": 630,"name": "fa fa-backward"},
            {"id": 631,"name": "fa fa-compress"},
            {"id": 632,"name": "fa fa-eject"},
            {"id": 633,"name": "fa fa-expand"},
            {"id": 634,"name": "fa fa-fast-backward"},
            {"id": 635,"name": "fa fa-fast-forward"},
            {"id": 636,"name": "fa fa-forward"},
            {"id": 637,"name": "fa fa-pause"},
            {"id": 638,"name": "fa fa-pause-circle"},
            {"id": 639,"name": "fa fa-pause-circle-o"},
            {"id": 640,"name": "fa fa-play"},
            {"id": 641,"name": "fa fa-play-circle"},
            {"id": 642,"name": "fa fa-play-circle-o"},
            {"id": 643,"name": "fa fa-step-backward"},
            {"id": 644,"name": "fa fa-step-forward"},
            {"id": 645,"name": "fa fa-stop"},
            {"id": 646,"name": "fa fa-stop-circle"},
            {"id": 647,"name": "fa fa-stop-circle-o"},
            {"id": 648,"name": "fa fa-youtube-play"},
            {"id": 649,"name": "fa fa-500px"},
            {"id": 650,"name": "fa fa-adn"},
            {"id": 651,"name": "fa fa-amazon"},
            {"id": 652,"name": "fa fa-android"},
            {"id": 653,"name": "fa fa-angellist"},
            {"id": 654,"name": "fa fa-apple"},
            {"id": 655,"name": "fa fa-behance"},
            {"id": 656,"name": "fa fa-behance-square"},
            {"id": 657,"name": "fa fa-bitbucket"},
            {"id": 658,"name": "fa fa-bitbucket-square"},
            {"id": 659,"name": "fa fa-black-tie"},
            {"id": 660,"name": "fa fa-buysellads"},
            {"id": 661,"name": "fa fa-chrome"},
            {"id": 662,"name": "fa fa-codepen"},
            {"id": 663,"name": "fa fa-codiepie"},
            {"id": 664,"name": "fa fa-connectdevelop"},
            {"id": 665,"name": "fa fa-contao"},
            {"id": 666,"name": "fa fa-css3"},
            {"id": 667,"name": "fa fa-dashcube"},
            {"id": 668,"name": "fa fa-delicious"},
            {"id": 669,"name": "fa fa-deviantart"},
            {"id": 670,"name": "fa fa-digg"},
            {"id": 671,"name": "fa fa-dribbble"},
            {"id": 672,"name": "fa fa-dropbox"},
            {"id": 673,"name": "fa fa-drupal"},
            {"id": 674,"name": "fa fa-edge"},
            {"id": 675,"name": "fa fa-empire"},
            {"id": 676,"name": "fa fa-envira"},
            {"id": 677,"name": "fa fa-expeditedssl"},
            {"id": 678,"name": "fa fa-fa"},
            {"id": 679,"name": "fa fa-facebook"},
            {"id": 680,"name": "fa fa-facebook-f"},
            {"id": 681,"name": "fa fa-facebook-official"},
            {"id": 682,"name": "fa fa-facebook-square"},
            {"id": 683,"name": "fa fa-firefox"},
            {"id": 684,"name": "fa fa-first-order"},
            {"id": 685,"name": "fa fa-flickr"},
            {"id": 686,"name": "fa fa-fonticons"},
            {"id": 687,"name": "fa fa-fort-awesome"},
            {"id": 688,"name": "fa fa-forumbee"},
            {"id": 689,"name": "fa fa-foursquare"},
            {"id": 690,"name": "fa fa-ge"},
            {"id": 691,"name": "fa fa-get-pocket"},
            {"id": 692,"name": "fa fa-git"},
            {"id": 693,"name": "fa fa-git-square"},
            {"id": 694,"name": "fa fa-github"},
            {"id": 695,"name": "fa fa-github-alt"},
            {"id": 696,"name": "fa fa-github-square"},
            {"id": 697,"name": "fa fa-gitlab"},
            {"id": 698,"name": "fa fa-gittip"},
            {"id": 699,"name": "fa fa-glide"},
            {"id": 700,"name": "fa fa-glide-g"},
            {"id": 701,"name": "fa fa-google"},
            {"id": 702,"name": "fa fa-google-plus"},
            {"id": 703,"name": "fa fa-google-plus-circle"},
            {"id": 704,"name": "fa fa-google-plus-official"},
            {"id": 705,"name": "fa fa-google-plus-square"},
            {"id": 706,"name": "fa fa-gratipay"},
            {"id": 707,"name": "fa fa-hacker-news"},
            {"id": 708,"name": "fa fa-houzz"},
            {"id": 709,"name": "fa fa-html5"},
            {"id": 710,"name": "fa fa-instagram"},
            {"id": 711,"name": "fa fa-internet-explorer"},
            {"id": 712,"name": "fa fa-ioxhost"},
            {"id": 713,"name": "fa fa-joomla"},
            {"id": 714,"name": "fa fa-jsfiddle"},
            {"id": 715,"name": "fa fa-lastfm"},
            {"id": 716,"name": "fa fa-lastfm-square"},
            {"id": 717,"name": "fa fa-leanpub"},
            {"id": 718,"name": "fa fa-linkedin"},
            {"id": 719,"name": "fa fa-linkedin-square"},
            {"id": 720,"name": "fa fa-linux"},
            {"id": 721,"name": "fa fa-maxcdn"},
            {"id": 722,"name": "fa fa-meanpath"},
            {"id": 723,"name": "fa fa-medium"},
            {"id": 724,"name": "fa fa-mixcloud"},
            {"id": 725,"name": "fa fa-modx"},
            {"id": 726,"name": "fa fa-odnoklassniki"},
            {"id": 727,"name": "fa fa-odnoklassniki-square"},
            {"id": 728,"name": "fa fa-opencart"},
            {"id": 729,"name": "fa fa-openid"},
            {"id": 730,"name": "fa fa-opera"},
            {"id": 731,"name": "fa fa-optin-monster"},
            {"id": 732,"name": "fa fa-pagelines"},
            {"id": 733,"name": "fa fa-pied-piper"},
            {"id": 734,"name": "fa fa-pied-piper-alt"},
            {"id": 735,"name": "fa fa-pied-piper-pp"},
            {"id": 736,"name": "fa fa-pinterest"},
            {"id": 737,"name": "fa fa-pinterest-p"},
            {"id": 738,"name": "fa fa-pinterest-square"},
            {"id": 739,"name": "fa fa-product-hunt"},
            {"id": 740,"name": "fa fa-qq"},
            {"id": 741,"name": "fa fa-ra"},
            {"id": 742,"name": "fa fa-rebel"},
            {"id": 743,"name": "fa fa-reddit"},
            {"id": 744,"name": "fa fa-reddit-alien"},
            {"id": 745,"name": "fa fa-reddit-square"},
            {"id": 746,"name": "fa fa-renren"},
            {"id": 747,"name": "fa fa-resistance"},
            {"id": 748,"name": "fa fa-safari"},
            {"id": 749,"name": "fa fa-scribd"},
            {"id": 750,"name": "fa fa-sellsy"},
            {"id": 751,"name": "fa fa-shirtsinbulk"},
            {"id": 752,"name": "fa fa-simplybuilt"},
            {"id": 753,"name": "fa fa-skyatlas"},
            {"id": 754,"name": "fa fa-skype"},
            {"id": 755,"name": "fa fa-slack"},
            {"id": 756,"name": "fa fa-slideshare"},
            {"id": 757,"name": "fa fa-snapchat"},
            {"id": 758,"name": "fa fa-snapchat-ghost"},
            {"id": 759,"name": "fa fa-snapchat-square"},
            {"id": 760,"name": "fa fa-soundcloud"},
            {"id": 761,"name": "fa fa-spotify"},
            {"id": 762,"name": "fa fa-stack-exchange"},
            {"id": 763,"name": "fa fa-stack-overflow"},
            {"id": 764,"name": "fa fa-steam"},
            {"id": 765,"name": "fa fa-steam-square"},
            {"id": 766,"name": "fa fa-stumbleupon"},
            {"id": 767,"name": "fa fa-stumbleupon-circle"},
            {"id": 768,"name": "fa fa-tencent-weibo"},
            {"id": 769,"name": "fa fa-themeisle"},
            {"id": 770,"name": "fa fa-trello"},
            {"id": 771,"name": "fa fa-tripadvisor"},
            {"id": 772,"name": "fa fa-tumblr"},
            {"id": 773,"name": "fa fa-tumblr-square"},
            {"id": 774,"name": "fa fa-twitch"},
            {"id": 775,"name": "fa fa-twitter"},
            {"id": 776,"name": "fa fa-twitter-square"},
            {"id": 777,"name": "fa fa-usb"},
            {"id": 778,"name": "fa fa-viacoin"},
            {"id": 779,"name": "fa fa-viadeo"},
            {"id": 780,"name": "fa fa-viadeo-square"},
            {"id": 781,"name": "fa fa-vimeo"},
            {"id": 782,"name": "fa fa-vimeo-square"},
            {"id": 783,"name": "fa fa-vine"},
            {"id": 784,"name": "fa fa-vk"},
            {"id": 785,"name": "fa fa-wechat"},
            {"id": 786,"name": "fa fa-weibo"},
            {"id": 787,"name": "fa fa-weixin"},
            {"id": 788,"name": "fa fa-whatsapp"},
            {"id": 789,"name": "fa fa-wikipedia-w"},
            {"id": 790,"name": "fa fa-windows"},
            {"id": 791,"name": "fa fa-wordpress"},
            {"id": 792,"name": "fa fa-wpbeginner"},
            {"id": 793,"name": "fa fa-wpforms"},
            {"id": 794,"name": "fa fa-xing"},
            {"id": 795,"name": "fa fa-xing-square"},
            {"id": 796,"name": "fa fa-y-combinator"},
            {"id": 797,"name": "fa fa-y-combinator-square"},
            {"id": 798,"name": "fa fa-yahoo"},
            {"id": 799,"name": "fa fa-yc"},
            {"id": 800,"name": "fa fa-yc-square"},
            {"id": 801,"name": "fa fa-yelp"},
            {"id": 802,"name": "fa fa-yoast"},
            {"id": 803,"name": "fa fa-youtube"},
            {"id": 804,"name": "fa fa-youtube-square"},
            {"id": 805,"name": "fa fa-h-square"},
            {"id": 806,"name": "fa fa-hospital-o"},
            {"id": 807,"name": "fa fa-medkit"},
            {"id": 808,"name": "fa fa-stethoscope"},
            {"id": 809,"name": "fa fa-user-md"}
        ];
    }
}
</script>

<style scoped>
.icon-box{
    height:200px;
    overflow-y:auto;
}
.icon-btns{
    text-align: right;
    padding-top:10px;
    padding-right: 20px;
}
.icon.el-button{
    margin-left:10px;
    margin-top:10px;
    width:40px;
    height:25px;
}
.el-input__suffix {
  pointer-events: all;
  cursor: pointer;
  line-height: normal !important;
  height:auto;
}
.el-input__icon {
  height: auto;
  width: 25px;
  text-align: center;
  -webkit-transition: all 0.3s;
  transition: all 0.3s;
  line-height: 40px;
}
</style>
